AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/NonDeterministicRequireOrder:
  Enbled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
